spring.application.name=Entrega3

#Modificar para la prueba

spring.datasource.url=jdbc:mysql://localhost:3306/Torneo_DBspring?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=mi_password_secreto

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true